#!/bin/bash
# Small script to upload files to https://mclo.gs, requires jq to be installed
# Example usage: log latest.log
# Example output: https://mclo.gs/ABCDEFG
content="content=$(cat $1)"
request=$(curl --location --request POST 'https://api.mclo.gs/1/log' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode "$content" 2>/dev/null | jq -r '.id')
echo "https://mclo.gs/$request"
