#!/bin/bash
# Small script to upload files to https://mclo.gs, requires jq to be installed
# Example usage: log latest.log
# Example output: https://mclo.gs/ABCDEFG
tail -500 -- "$1" | curl -sSL --data-urlencode content@- https://api.mclo.gs/1/log | jq -r '.url'
